PROVIDER_CATEGORY_MAP = {
    "openai": "llm",
    "groq": "llm",
    "anthropic": "llm",
    "gemini": "llm",
    "openrouter": "llm",
    "mistral": "llm",
    "together": "llm",
    "fireworks": "llm",
    "anyscale": "llm",
    "deepinfra": "llm",
    "nebius": "llm",
    "cohere": "llm",
    "ai21": "llm",
    "perplexity": "llm",
    "deepseek": "llm",
    "qwen": "llm",
    "grok": "llm",
    "replicate": "llm",
    "baseten": "llm",
    "huggingface": "llm",
    "pinecone": "vector_db",
    "weaviate": "vector_db",
    "qdrant": "vector_db",
    "milvus": "vector_db",
    "neondb": "database",
    "xata": "database",
    "airbyte": "data_engineering",
    "dbt": "data_engineering",
    "fivetran": "data_engineering",
    "github": "devops",
    "gitlab": "devops",
    "bitbucket": "devops",
    "supabase": "database",
    "mongodb": "database",
    "planetscale": "database",
    "dagster": "data_engineering",
    "prefect": "data_engineering",
    "astronomer": "data_engineering",
    "vercel": "devops",
    "render": "devops",
    "cloudflare": "devops",
    "stripe": "apis",
    "twilio": "apis",
    "sendgrid": "apis",
    "slack": "apis",
    "notion": "apis",
    "shopify": "apis",
    "cockroachdb": "database",
    "lancedb": "vector_db",
    "meltano": "data_engineering",
    "railway": "devops",
    "discord": "apis",
    "postgres": "database",
    "snowflake": "database",
}


CATEGORY_PROVIDER_CONFIG = {
    "vector_db": {
        "pinecone": {"base_url": "https://api.pinecone.io", "auth_header": "Api-Key"},
        "weaviate": {"base_url": None, "auth_header": "Authorization", "bearer": True},
        "qdrant": {"base_url": "https://api.cloud.qdrant.io", "auth_header": "api-key"},
        "milvus": {"base_url": None, "auth_header": "Authorization", "bearer": True},
        "lancedb": {"base_url": None, "auth_header": "Authorization", "bearer": True},
    },
    "database": {
        "neondb": {"base_url": "https://console.neon.tech/api/v2", "auth_header": "Authorization", "bearer": True},
        "xata": {"base_url": "https://api.xata.io", "auth_header": "Authorization", "bearer": True},
        "supabase": {"base_url": "https://api.supabase.com/v1", "auth_header": "apikey"},
        "mongodb": {"base_url": None, "auth_header": "api-key"},
        "planetscale": {"base_url": "https://api.planetscale.com/v1", "auth_header": "Authorization", "bearer": True},
        "cockroachdb": {"base_url": "https://cockroachlabs.cloud/api/v1", "auth_header": "Authorization", "bearer": True},
        "postgres": {"base_url": None, "auth_header": "Authorization", "bearer": True},
        "snowflake": {"base_url": None, "auth_header": "Authorization", "bearer": True},
    },
    "data_engineering": {
        "airbyte": {"base_url": "https://api.airbyte.com/v1", "auth_header": "Authorization", "bearer": True},
        "dbt": {"base_url": "https://cloud.getdbt.com/api/v2", "auth_header": "Authorization", "bearer": True},
        "fivetran": {"base_url": "https://api.fivetran.com/v1", "auth_header": "Authorization", "bearer": True},
        "dagster": {"base_url": None, "auth_header": "Authorization", "bearer": True},
        "prefect": {"base_url": "https://api.prefect.cloud/api", "auth_header": "Authorization", "bearer": True},
        "astronomer": {"base_url": None, "auth_header": "Authorization", "bearer": True},
        "meltano": {"base_url": None, "auth_header": "Authorization", "bearer": True},
    },
    "devops": {
        "github": {"base_url": "https://api.github.com", "auth_header": "Authorization", "bearer": True},
        "gitlab": {"base_url": "https://gitlab.com/api/v4", "auth_header": "Authorization", "bearer": True},
        "bitbucket": {"base_url": "https://api.bitbucket.org/2.0", "auth_header": "Authorization", "bearer": True},
        "vercel": {"base_url": "https://api.vercel.com", "auth_header": "Authorization", "bearer": True},
        "render": {"base_url": "https://api.render.com/v1", "auth_header": "Authorization", "bearer": True},
        "cloudflare": {"base_url": "https://api.cloudflare.com/client/v4", "auth_header": "Authorization", "bearer": True},
        "railway": {"base_url": "https://backboard.railway.app/graphql/v2", "auth_header": "Authorization", "bearer": True},
    },
    "apis": {
        "stripe": {"base_url": "https://api.stripe.com/v1", "auth_header": "Authorization", "bearer": True},
        "twilio": {"base_url": "https://api.twilio.com/2010-04-01", "auth_mode": "basic"},
        "sendgrid": {"base_url": "https://api.sendgrid.com/v3", "auth_header": "Authorization", "bearer": True},
        "slack": {"base_url": "https://slack.com/api", "auth_header": "Authorization", "bearer": True},
        "notion": {"base_url": "https://api.notion.com/v1", "auth_header": "Authorization", "bearer": True},
        "shopify": {"base_url": None, "auth_header": "X-Shopify-Access-Token"},
        "discord": {"base_url": "https://discord.com/api/v10", "auth_header": "Authorization", "bearer": True},
    },
}
